name: Hydra build status (Darwin)

on:
  schedule:
    - cron:  '0 6 * * *'
  workflow_dispatch:

env:
  NIX_CONFIG: "access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}"

jobs:
  check-hydra-build:

    strategy:
      fail-fast: false
      matrix:
        platform:
          - x86_64-darwin
          - aarch64-darwin


    name: Check build status
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Nix
        uses: cachix/install-nix-action@v25

      - name: Generate packages file
        run: >
          nix eval --json --file maintainer-packages.nix --arg showBroken false packages
          | jq '[.. | objects | select(has("name")) | .name]'
          > packages.json

      - name: Check build status
        run: >
          ./hydra-build-status.py --platforms ${{ matrix.platform }} --file packages.json
